---
availability_zone: melbourne-qh2-uom
instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: Group66
instance_flavor: uom.mse.2c9g
instance_name1: Nginx-node
instance_name2: Master-node
instance_name3: Slave-node1
instance_name4: Slave-node2
vol_name1: vol_Nginx
vol_name2: vol_Master
vol_name3: vol_Slave1
vol_name4: vol_Slave2
vol_size: 60
vol_nginx_size: 40
snapshot: snapshot

security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    
  - name: nginx
    description: "proxy access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: http
    description: "HTTP access"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb1
    description: "CouchDB access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb2
    description: "CouchDB access"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb3
    description: "CouchDB access"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb3
    description: "CouchDB access"
    protocol: tcp
    port_range_min: 4040
    port_range_max: 4040
    remote_ip_prefix: 0.0.0.0/0

  - name: flask
    description: "web access"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0

  - name: scope
    description: "monitor access"
    protocol: tcp
    port_range_min: 4040
    port_range_max: 4040
    remote_ip_prefix: 0.0.0.0/0