---
- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['xfsprogs', 'apt-transport-https', 'nginx', 'systemd', 'build-essential', 'python-setuptools', 'python3', 'unzip', 'vim', 'curl', 'git', 'python-pip', 'python-dev', 'python3-dev', 'python3-pip', 'libffi-dev', 'libssl-dev', 'net-tools', 'network-manager']
    state: present
    install_recommends: yes
    update_cache: yes

- name: Update pip
  tags: always
  become: yes
  pip:
    name: ['pip', 'uwsgi', 'couchdb', 'flask', 'pandas', 'numpy']
    state: latest

- name: upload the ip lookup txt file
  copy:
    src: ../../../nodes.txt
    dest: /home/ubuntu
    mode: 0777

- name: upload the configuration script
  copy:
    src: ./configuration.sh
    dest: /home/ubuntu
    mode: 0777

- name: execute the configuration script
  become: yes
  shell: /home/ubuntu/configuration.sh

